handle thrown exceptions in a task
nunomaduro/laravel-console-task pull request #8
Opened 2018-12-12 15:45 UTC by Broutard

At the moment, if an exception is thrown in a task, the task remains in "loading...".

This PR catch any exceptions in task callback, and throw back the exception after considering the task as failed.

2018-12-12 15:54 UTC, nunomaduro requested changes

2018-12-12 15:54 UTC, nunomaduro commented on src/LaravelConsoleTaskServiceProvider.php
> +                    } catch (\Exception $taskException) {
It's perfect. Can you add a test for this?

2018-12-14 10:41 UTC, Broutard commented
Test added

2018-12-17 21:19 UTC, merged

2018-12-17 21:19 UTC, nunomaduro commented
Thanks for this @Broutard !